# Generated by Django 4.0.5 on 2022-07-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_set_alter_question_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='model_answer',
            field=models.TextField(default='', max_length=100000),
        ),
    ]
