# Generated by Django 4.0.5 on 2022-07-01 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_question_model_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='set',
            new_name='question_set',
        ),
        migrations.AddField(
            model_name='set',
            name='question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grader.question'),
        ),
    ]
