# Generated by Django 4.0.5 on 2022-07-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0004_rename_set_question_question_set_set_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_set',
            new_name='set',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_id',
        ),
    ]
